---
# tasks file for acme-tiny-setup/

- name: Certificate renewal group
  group:
    name: '{{ app__acme__tiny__group }}'
    system: True

- name: Certificate renewal user
  user:
    name: '{{ app__acme__tiny__user }}'
    group: '{{ app__acme__tiny__group }}'
    system: True
    home: '{{ app__acme__tiny__home }}'
    createhome: yes

- name: Configuration directory
  file:
    path: '{{ app__acme__tiny__config_dir }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Certificate, challenge and logging directory
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ app__acme__tiny__user }}'
    group: '{{ app__acme__tiny__group }}'
    mode: '0755'
  with_items:
    - '{{ app__acme__tiny__challenge_dir }}'
    - '{{ app__acme__tiny__log_dir }}'
    - '{{ app__acme__tiny__cert_dir }}'

- name: Account key permissions
  file:
    path: '{{ app__acme__tiny__config_dir }}/{{ app__acme__tiny__account_key }}'
    owner: 'root'
    group: '{{ app__acme__tiny__group }}'
    mode: '0640'

- name: Download letsencrypt CA and intermediate certificates
  get_url:
    url: '{{ item.url }}'
    dest: '{{ app__acme__tiny__config_dir }}/{{ item.file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ app__acme__tiny__letsencrypt_certs }}'

- name: Private key
  shell: /usr/bin/openssl genrsa '{{ app__acme__tiny__key_length }}' > '{{ app__acme__tiny__key }}'
  args:
    creates: '{{ acme_tiny__key }}'

- name: Private key permissions
  file:
    path: '{{ app__acme__tiny__key }}'
    owner: 'root'
    group: '{{ app__acme__tiny__group }}'
    mode: '0640'

- name: Certificate request
  shell: '/usr/bin/openssl req -new -sha256 -key {{ app__acme__tiny__key }} -subj "/CN={{ app__acme__tiny__domain }}" > {{ app__acme__tiny__request }}'
  args:
    creates: '{{ app__acme__tiny__request }}'
  when: app__acme__tiny__domain is string

- name: Multi-domain certificate request
  shell: '/usr/bin/openssl req -new -sha256 -key {{ app__acme__tiny__key }} -subj "/" -reqexts SAN -config <(cat {{ app__acme__tiny__openssl_config }} <(printf "[SAN]\nsubjectAltName=DNS:{{ app__acme__tiny__domain | join(",DNS:") }}")) > {{ app__acme__tiny__request }}'
  args:
    executable: '/bin/bash'
    creates: '{{ app__acme__tiny__request }}'
  when: app__acme__tiny__domain is iterable and not app__acme__tiny__domain is string
  failed_when: False

